### PR TITLE
SoftAP basic commands and AP/STA mode switching

### PR DESCRIPTION
**Pull request by JAndrassy**

### CODE REVIEW

**Comment by JiriBilek** [comment]
Thanks a lot, I will review the PR ASAP.

**Comment by SamGeens** [comment]
I was working aswell on this for a while now, haven't had time to finish this. Is it okay if I check the differences and add extra stuff? I had a few more commands already implemented.

**Comment by JAndrassy** [comment]
@SamGeens you could add the additional commands after this PR is merged.
I tested and compared the behavior with the standard AT firmware, but it is always good to to have somebody else to test.
and of course we can discuss the differences in our implementations.

one thing I omitted in this PR is a check if the required mode STA/AP was activated before an STA/AP settings AT command. The WiFi library functions start the STA/AP so there will be no error, just the behavior is different than the standard AT firmware.
I plan to add this checks as separate PR.

**Comment by JAndrassy** [comment]
@JiriBilek as I write in previous comment, the normal AT firmware checks mode and returns ERROR if the right mode is not turned on for the command. ATMod now automatically turns the required mode on because that is how the esp8266 WiFi library works.
should I add the checks?

**Comment by JiriBilek** [comment]
Which commands would be affected by this check?

**Comment by JAndrassy** [comment]
> Which commands would be affected by this check?

AT_CWLAP
AT+CWLAPOPT
AT+CWJAP
AT+CIPSTA
AT+CIPDNS
AT+CWDHCP
AT+CWHOSTNAME
AT+CWSAP
AT+CIPAP

**Comment by JiriBilek** [comment]
Ouch, quite a few :)
Juraj, if you be so kind I'd be happy if you add the checks.
Thanks.

**Pull request merged**
