### PR TITLE
Ethernet support

### PR DESCRIPTION
**Pull request by JAndrassy**
The Ethernet commands are:

*  AT+CIPETHMAC - similar to AT+CIPSTAMAC - setting and query MAC address
*  AT+CIPETH - similar to AT+CIPSTA - static IP configuration
* AT+CEHOSTNAME - similar to AT+CIHOSTNAME - hostname sent in DHCP request
* AT+CWDHCP is enhanced by enabling/disabling DHCP on the Ethernet interface

### CODE REVIEW

**Comment by JAndrassy** [comment]
please merge PR https://github.com/JiriBilek/ESP_ATMod/pull/33 first

**Comment by JAndrassy** [comment]
sorry. what changes? I see no changes. maybe they were lost when I force pushed from local repo

**Comment by JiriBilek** [comment]
It's https://github.com/JAndrassy/ESP_ATMod/pull/2

**Comment by JAndrassy** [comment]
I didn't get any notification from GitGub about that PR. it is merged now

**Comment by JiriBilek** [comment]
Thanks, #33 merged now into master

**Comment by JAndrassy** [comment]
I did the rebase and I removed the draft status of this PR

**Comment by JiriBilek** [comment]
I am not able to test it, so please tell me when it is ready to merge.
Please set the version to 0.5.0 as this is a substantial change to the app.

**Comment by JAndrassy** [comment]
ready

**Comment by JiriBilek** [comment]
Thanks!

**Pull request merged**
